# Test 2024-06-26 at 03:59:50

name: Test
run-name: Silicon Chip

on:
  push:
    paths:
      - '**/main.yml'

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - name: 'JDK 22'
      uses: oracle-actions/setup-java@v1
      with:
        website: jdk.java.net

    - name: Risc V
      run: |
        java RiscV.java
